/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AdminChoiceRouteImport } from './routes/admin-choice'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmRapportsRouteImport } from './routes/crm.rapports'
import { Route as CrmParametresRouteImport } from './routes/crm.parametres'
import { Route as CrmPaiementsRouteImport } from './routes/crm.paiements'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmFamillesRouteImport } from './routes/crm.familles'
import { Route as CrmDashboardRouteImport } from './routes/crm.dashboard'
import { Route as CrmCommunicationsRouteImport } from './routes/crm.communications'
import { Route as AdminRendezVousRouteImport } from './routes/admin.rendez-vous'
import { Route as AdminPlanningRouteImport } from './routes/admin.planning'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChoiceRoute = AdminChoiceRouteImport.update({
  id: '/admin-choice',
  path: '/admin-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRapportsRoute = CrmRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => CrmRoute,
} as any)
const CrmParametresRoute = CrmParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPaiementsRoute = CrmPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmFamillesRoute = CrmFamillesRouteImport.update({
  id: '/familles',
  path: '/familles',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDashboardRoute = CrmDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCommunicationsRoute = CrmCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => CrmRoute,
} as any)
const AdminRendezVousRoute = AdminRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanningRoute = AdminPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/crm': typeof CrmRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/crm/communications': typeof CrmCommunicationsRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/familles': typeof CrmFamillesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/paiements': typeof CrmPaiementsRoute
  '/crm/parametres': typeof CrmParametresRoute
  '/crm/rapports': typeof CrmRapportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/crm': typeof CrmRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/crm/communications': typeof CrmCommunicationsRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/familles': typeof CrmFamillesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/paiements': typeof CrmPaiementsRoute
  '/crm/parametres': typeof CrmParametresRoute
  '/crm/rapports': typeof CrmRapportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/crm': typeof CrmRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/planning': typeof AdminPlanningRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/crm/communications': typeof CrmCommunicationsRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/familles': typeof CrmFamillesRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/crm/paiements': typeof CrmPaiementsRoute
  '/crm/parametres': typeof CrmParametresRoute
  '/crm/rapports': typeof CrmRapportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-choice'
    | '/crm'
    | '/landing'
    | '/login'
    | '/admin/commandes'
    | '/admin/dashboard'
    | '/admin/planning'
    | '/admin/rendez-vous'
    | '/crm/communications'
    | '/crm/dashboard'
    | '/crm/familles'
    | '/crm/leads'
    | '/crm/paiements'
    | '/crm/parametres'
    | '/crm/rapports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-choice'
    | '/crm'
    | '/landing'
    | '/login'
    | '/admin/commandes'
    | '/admin/dashboard'
    | '/admin/planning'
    | '/admin/rendez-vous'
    | '/crm/communications'
    | '/crm/dashboard'
    | '/crm/familles'
    | '/crm/leads'
    | '/crm/paiements'
    | '/crm/parametres'
    | '/crm/rapports'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-choice'
    | '/crm'
    | '/landing'
    | '/login'
    | '/admin/commandes'
    | '/admin/dashboard'
    | '/admin/planning'
    | '/admin/rendez-vous'
    | '/crm/communications'
    | '/crm/dashboard'
    | '/crm/familles'
    | '/crm/leads'
    | '/crm/paiements'
    | '/crm/parametres'
    | '/crm/rapports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminChoiceRoute: typeof AdminChoiceRoute
  CrmRoute: typeof CrmRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-choice': {
      id: '/admin-choice'
      path: '/admin-choice'
      fullPath: '/admin-choice'
      preLoaderRoute: typeof AdminChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/rapports': {
      id: '/crm/rapports'
      path: '/rapports'
      fullPath: '/crm/rapports'
      preLoaderRoute: typeof CrmRapportsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/parametres': {
      id: '/crm/parametres'
      path: '/parametres'
      fullPath: '/crm/parametres'
      preLoaderRoute: typeof CrmParametresRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/paiements': {
      id: '/crm/paiements'
      path: '/paiements'
      fullPath: '/crm/paiements'
      preLoaderRoute: typeof CrmPaiementsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/familles': {
      id: '/crm/familles'
      path: '/familles'
      fullPath: '/crm/familles'
      preLoaderRoute: typeof CrmFamillesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/dashboard': {
      id: '/crm/dashboard'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof CrmDashboardRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/communications': {
      id: '/crm/communications'
      path: '/communications'
      fullPath: '/crm/communications'
      preLoaderRoute: typeof CrmCommunicationsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/admin/rendez-vous': {
      id: '/admin/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AdminRendezVousRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planning': {
      id: '/admin/planning'
      path: '/planning'
      fullPath: '/admin/planning'
      preLoaderRoute: typeof AdminPlanningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPlanningRoute: typeof AdminPlanningRoute
  AdminRendezVousRoute: typeof AdminRendezVousRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCommandesRoute: AdminCommandesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPlanningRoute: AdminPlanningRoute,
  AdminRendezVousRoute: AdminRendezVousRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CrmRouteChildren {
  CrmCommunicationsRoute: typeof CrmCommunicationsRoute
  CrmDashboardRoute: typeof CrmDashboardRoute
  CrmFamillesRoute: typeof CrmFamillesRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmPaiementsRoute: typeof CrmPaiementsRoute
  CrmParametresRoute: typeof CrmParametresRoute
  CrmRapportsRoute: typeof CrmRapportsRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCommunicationsRoute: CrmCommunicationsRoute,
  CrmDashboardRoute: CrmDashboardRoute,
  CrmFamillesRoute: CrmFamillesRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmPaiementsRoute: CrmPaiementsRoute,
  CrmParametresRoute: CrmParametresRoute,
  CrmRapportsRoute: CrmRapportsRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminChoiceRoute: AdminChoiceRoute,
  CrmRoute: CrmRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
