/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRendezVousRouteImport } from './routes/dashboard.rendez-vous'
import { Route as DashboardRapportsRouteImport } from './routes/dashboard.rapports'
import { Route as DashboardPlanificationsRouteImport } from './routes/dashboard.planifications'
import { Route as DashboardPaiementsRouteImport } from './routes/dashboard.paiements'
import { Route as DashboardFamillesRouteImport } from './routes/dashboard.familles'
import { Route as DashboardAffichesRouteImport } from './routes/dashboard.affiches'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRendezVousRoute = DashboardRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRapportsRoute = DashboardRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanificationsRoute = DashboardPlanificationsRouteImport.update({
  id: '/planifications',
  path: '/planifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaiementsRoute = DashboardPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamillesRoute = DashboardFamillesRouteImport.update({
  id: '/familles',
  path: '/familles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAffichesRoute = DashboardAffichesRouteImport.update({
  id: '/affiches',
  path: '/affiches',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/rendez-vous': typeof DashboardRendezVousRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/rendez-vous': typeof DashboardRendezVousRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/rendez-vous': typeof DashboardRendezVousRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/affiches'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/rendez-vous'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/affiches'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/rendez-vous'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/affiches'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/rendez-vous'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rendez-vous': {
      id: '/dashboard/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/dashboard/rendez-vous'
      preLoaderRoute: typeof DashboardRendezVousRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rapports': {
      id: '/dashboard/rapports'
      path: '/rapports'
      fullPath: '/dashboard/rapports'
      preLoaderRoute: typeof DashboardRapportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planifications': {
      id: '/dashboard/planifications'
      path: '/planifications'
      fullPath: '/dashboard/planifications'
      preLoaderRoute: typeof DashboardPlanificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/paiements': {
      id: '/dashboard/paiements'
      path: '/paiements'
      fullPath: '/dashboard/paiements'
      preLoaderRoute: typeof DashboardPaiementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/familles': {
      id: '/dashboard/familles'
      path: '/familles'
      fullPath: '/dashboard/familles'
      preLoaderRoute: typeof DashboardFamillesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/affiches': {
      id: '/dashboard/affiches'
      path: '/affiches'
      fullPath: '/dashboard/affiches'
      preLoaderRoute: typeof DashboardAffichesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAffichesRoute: typeof DashboardAffichesRoute
  DashboardFamillesRoute: typeof DashboardFamillesRoute
  DashboardPaiementsRoute: typeof DashboardPaiementsRoute
  DashboardPlanificationsRoute: typeof DashboardPlanificationsRoute
  DashboardRapportsRoute: typeof DashboardRapportsRoute
  DashboardRendezVousRoute: typeof DashboardRendezVousRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAffichesRoute: DashboardAffichesRoute,
  DashboardFamillesRoute: DashboardFamillesRoute,
  DashboardPaiementsRoute: DashboardPaiementsRoute,
  DashboardPlanificationsRoute: DashboardPlanificationsRoute,
  DashboardRapportsRoute: DashboardRapportsRoute,
  DashboardRendezVousRoute: DashboardRendezVousRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
